version : '3.8'
services:
  healthcare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    environment:
      RDS_URL: mysql
    networks:
      - saman-network
    
  mysql:
    image: mysql:8-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: saman
      MYSQL_PASSWORD: saman
      MYSQL_HOST: mysql
    volumes:
      - myvolume:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - saman-network
volumes:
  myvolume:
  
networks:
  saman-network:
    